"""ADE20K-150 -> photographic region-type taxonomy (R2 spike).

The region-type *map* is genre-agnostic: SegFormer labels a building as
``structure`` always; whether ``structure`` counts as the *subject* is decided
later, genre-conditionally, outside this module.

The mapping is generated by keyword rules from the model's own ``id2label`` and
is intended to be reviewed/edited — ``export_segformer_dual.py`` prints the full
table and writes it to ``region_lut.json`` so a human can correct any class
before the extraction pass consumes it.
"""

from __future__ import annotations

import re

# Histogram / channel order. ``face`` is reserved for a YuNet overlay (never
# emitted by SegFormer); ``other`` is the catch-all (indoor furniture/clutter).
REGION_TYPES: list[str] = [
    "sky",
    "water",
    "vegetation",
    "ground",
    "structure",
    "subject",
    "face",
    "other",
]

# Explicit overrides for labels whose keywords would otherwise misfire
# (e.g. "pool table" contains "pool" but is furniture, not water).
_OVERRIDES: dict[str, str] = {
    "pool table": "other",
    "swimming pool": "water",
    "field": "vegetation",
    "stage": "other",
    "screen door": "structure",
    "step": "ground",
    "stairway": "structure",
    "land": "ground",
}

# Checked in order; first rule whose keyword set intersects the label's tokens
# wins. Anything unmatched falls through to "other".
_RULES: list[tuple[str, set[str]]] = [
    ("sky", {"sky"}),
    ("water", {"water", "sea", "river", "lake", "waterfall", "fountain", "pond", "pool"}),
    ("vegetation", {"tree", "grass", "plant", "flower", "palm", "bush", "hedge", "vegetation"}),
    ("ground", {
        "earth", "ground", "sand", "road", "sidewalk", "pavement", "path",
        "mountain", "hill", "rock", "stone", "dirt", "gravel", "runway", "field",
    }),
    ("structure", {
        "building", "house", "skyscraper", "wall", "bridge", "tower", "fence",
        "hut", "hovel", "grandstand", "stairs", "stairway", "stair", "column",
        "railing", "awning", "pier", "booth", "arcade", "canopy", "tent",
    }),
    ("subject", {
        "person", "animal", "car", "boat", "bus", "truck", "airplane", "plane",
        "bicycle", "bike", "motorbike", "minibike", "van", "ship", "bird",
        "cat", "dog", "horse", "cow", "sheep", "food", "ball", "sculpture",
        "statue",
    }),
]


def _tokens(label: str) -> set[str]:
    return set(re.split(r"[^a-z]+", label.lower().strip())) - {""}


def classify_label(label: str) -> str:
    """Map one ADE20K class name to a region-type."""
    key = label.lower().strip()
    if key in _OVERRIDES:
        return _OVERRIDES[key]
    toks = _tokens(label)
    for rtype, kws in _RULES:
        if toks & kws:
            return rtype
    return "other"


def build_lut(id2label: dict[int, str]) -> dict[int, str]:
    """Build {class_index: region_type} from a model's id2label mapping."""
    return {int(idx): classify_label(name) for idx, name in id2label.items()}


def region_index(region_type: str) -> int:
    return REGION_TYPES.index(region_type)
